name: Code Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.18.1/checkstyle-10.18.1-all.jar

      - name: Run Code Quality Check
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        run: |
          python runner.py
